# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  # Enable version updates for python
  - package-ecosystem: "pip"
    # Look for a `requirements` in the `root` directory
    directory: "/"
    # Check for updates once a month
    schedule:
      interval: "monthly"
    groups:
      pip:
        patterns:
          - "*"
    # Labels on pull requests for version updates only
    labels: ["maintenance"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    # Check for updates once a monthly
    schedule:
      interval: "monthly"
    groups:
      actions:
        patterns:
          - "*"
    # Labels on pull requests for version updates only
    labels: ["maintenance"]
