language: python
dist: xenial
sudo: true
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.7-dev
  - pypy2.7-5.10.0
  - pypy3.5
env:
  - PYTEST=4.1.1
  - PYTEST=4.2.1
  - PYTEST=4.3.1
  - PYTEST=4.4.2
  - PYTEST=4.5.0  
install:
  - pip install -q pytest==$PYTEST
  - pip install -q -e .
script: py.test
