language: python
dist: xenial
sudo: true
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.7-dev
  - pypy2.7
  - pypy3.5
env:
  - PYTEST=2.8.7
  - PYTEST=2.9.2
  - PYTEST=3.0.7
  - PYTEST=3.1.3
  - PYTEST=3.2.1
  - PYTEST=3.3.2
  - PYTEST=3.4.2
  - PYTEST=3.5.1
  - PYTEST=3.6.3
  - PYTEST=3.7.4
  - PYTEST=3.8.2
  - PYTEST=3.9.3
  - PYTEST=3.10.0
install:
  - pip install -q pytest==$PYTEST
  - pip install -q -e .
script: py.test
